- name: Generate snake
  uses: Platane/snk@v3
  with:
    github_user_name: ${{ github.repository_owner }}
    outputs: |
      dist/snake.svg
      dist/snake-dark.svg?palette=github-dark
      dist/snake-ocean.svg?color_snake=#00D4FF&color_dots=#161B22,#0E4429,#006D32,#26A641,#39D353
